services:
  
  mqttbroker:
    image: eclipse-mosquitto:1.6.13 # the image the container is build from
    container_name: mqttbroker
    ports:
      - "8883:1883"  
    networks:
      - hydroplant
  
  tick_gen:
    build: ./src/tick_gen # the path to the dockerfile the container has to be build from
    container_name: tick_gen
    networks:
      - hydroplant
  
  turbine_sim:
    build: ./src/turbine_sim
    container_name: turbine_sim
    networks:
      - hydroplant
  
  dashboard:
    build: ./src/dashboard
    container_name: dashboard
    ports:
      - "1880:1880"  
    networks:
      - hydroplant

  climate_gen_hamburg:
    build: ./src/climate_gen_hamburg
    container_name: climate_gen_hamburg
    networks:
      - hydroplant

  request_hydrogen_gen:
    build: ./src/request_hydrogen_gen
    container_name: request_hydrogen_gen
    networks:
      - hydroplant

  wind_power_plant_0:
    build: ./src/wind_power_plant_0
    container: wind_power_plant_0
    networks:
      - hydroplant

  wind_power_plant_1:
    build: ./src/wind_power_plant_1
    container: wind_power_plant_1
    networks:
      - hydroplant

  wind_power_sum:
    build: ./src/wind_power_sum
    container: wind_power_sum
    networks:
      - hydroplant

# Define a shared network for the containers
networks:
  hydroplant:
    driver: bridge